# Dependabot configuration for AbyssIRC Server
# File must be placed at: .github/dependabot.yml

version: 2
updates:
  # Configuration for NuGet packages
  - package-ecosystem: "nuget"
    directory: "/"  # Repository root where .csproj files are located
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "nuget"
    assignees:
      - "tgiachi"  # Your GitHub username
    commit-message:
      prefix: "nuget"
      include: "scope"
    # Ignore specific updates (optional)
    # ignore:
    #   - dependency-name: "Package.Name"
    #     versions: ["1.x", "2.x"]

  # Configuration for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
