name: Publish NuGet Packages

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-build

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Pack all NuGet projects
        run: |
          for project in $(find ./src -name "*.csproj"); do
            dotnet pack $project \
            --configuration Release \
            --no-build \
            --include-symbols \
            --output ./nupkgs
          done

      - name: Push packages to NuGet
        run: |
          dotnet nuget push ./nupkgs/*.nupkg \
          --api-key ${{ secrets.NUGET_KEY }} \
          --source https://api.nuget.org/v3/index.json \
          --skip-duplicate

      - name: Setup NuGet for GitHub Packages
        run: |
          dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Push packages to GitHub Packages
        run: |
          dotnet nuget push ./nupkgs/*.nupkg \
          --api-key ${{ secrets.GITHUB_TOKEN }} \
          --source github \
          --skip-duplicate
